SET SUBMISSION_FILE="submission.zip"
SET LIBRARIES="hlt"
SET BOT_FILE="MyBot.java"

IF EXIST %SUBMISSION_FILE% DEL /F %SUBMISSION_FILE%

"C:\Program Files\7-Zip\7z" a -tzip %SUBMISSION_FILE% %LIBRARIES% %BOT_FILE%